// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "support@ecanteen.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/customer": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve all customers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "Get all customers",
                "responses": {
                    "200": {
                        "description": "Customers list",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/entity.Customer"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Register a new customer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "Register customer",
                "parameters": [
                    {
                        "description": "Customer data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Customer"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Customer registered",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.Customer"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/handler.WebResponse"
                        }
                    }
                }
            }
        },
        "/customer/login": {
            "post": {
                "description": "Authenticate customer and get JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "Customer login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful with JWT token",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/handler.WebResponse"
                        }
                    }
                }
            }
        },
        "/customer/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Logout customer and invalidate token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "Customer logout",
                "responses": {
                    "200": {
                        "description": "Logout successful",
                        "schema": {
                            "$ref": "#/definitions/handler.WebResponse"
                        }
                    }
                }
            }
        },
        "/customer/{customerId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve customer details by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "Get customer by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Customer ID",
                        "name": "customerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Customer details",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.Customer"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Customer not found",
                        "schema": {
                            "$ref": "#/definitions/handler.WebResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update customer information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "Update customer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Customer ID",
                        "name": "customerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Customer data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Customer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Customer updated",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.Customer"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Customer not found",
                        "schema": {
                            "$ref": "#/definitions/handler.WebResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete customer by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "Delete customer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Customer ID",
                        "name": "customerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Customer deleted",
                        "schema": {
                            "$ref": "#/definitions/handler.WebResponse"
                        }
                    },
                    "404": {
                        "description": "Customer not found",
                        "schema": {
                            "$ref": "#/definitions/handler.WebResponse"
                        }
                    }
                }
            }
        },
        "/dashboard/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get comprehensive dashboard statistics including total sales, transactions, customers, monthly sales chart, and top 10 products",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get dashboard statistics",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Year for monthly sales data (default: current year)",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Dashboard statistics",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.DashboardStats"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.WebResponse"
                        }
                    }
                }
            }
        },
        "/kasir/login": {
            "post": {
                "description": "Authenticate kasir user and get JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "User login (Kasir)",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful with JWT token",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/handler.WebResponse"
                        }
                    }
                }
            }
        },
        "/kasir/logout": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Logout kasir user and invalidate token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "User logout (Kasir)",
                "responses": {
                    "200": {
                        "description": "Logout successful",
                        "schema": {
                            "$ref": "#/definitions/handler.WebResponse"
                        }
                    }
                }
            }
        },
        "/kasir/transaction": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new cashier transaction",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Create transaction",
                "parameters": [
                    {
                        "description": "Transaction data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Transaction"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Transaction created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.Transaction"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/handler.WebResponse"
                        }
                    }
                }
            }
        },
        "/kasir/transaction/{transId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve transaction details by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Get transaction by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID",
                        "name": "transId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transaction details",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.Transaction"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Transaction not found",
                        "schema": {
                            "$ref": "#/definitions/handler.WebResponse"
                        }
                    }
                }
            }
        },
        "/kasir/transaction_detail": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve transaction detail items",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Get transaction details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID",
                        "name": "trans_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transaction details",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/entity.TransactionDetail"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/kasir/version": {
            "get": {
                "description": "Get current admin application version",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Version"
                ],
                "summary": "Get admin app version",
                "responses": {
                    "200": {
                        "description": "Version info",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.VersionAdmin"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/order": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new order with order details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "Create a new customer order",
                "parameters": [
                    {
                        "description": "Order request payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.CreateOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Order created successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.CustomerOrder"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request or insufficient stock",
                        "schema": {
                            "$ref": "#/definitions/handler.WebResponse"
                        }
                    }
                }
            }
        },
        "/order_report": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get customer orders filtered by date range (start_date and/or end_date)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "Get order report by date range",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD format)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD format)",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Order report",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/entity.CustomerOrder"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request - start_date or end_date required",
                        "schema": {
                            "$ref": "#/definitions/handler.WebResponse"
                        }
                    }
                }
            }
        },
        "/products": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve all products with their variants",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Get all products",
                "responses": {
                    "200": {
                        "description": "Products list",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/entity.Product"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/shop/version": {
            "get": {
                "description": "Get current customer shop application version",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Version"
                ],
                "summary": "Get shop app version",
                "responses": {
                    "200": {
                        "description": "Version info",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.VersionShop"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/tempcart": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Add product variant to temporary cart",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Add item to cart",
                "parameters": [
                    {
                        "description": "Cart item",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.TempCart"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Item added to cart",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.TempCart"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/handler.WebResponse"
                        }
                    }
                }
            }
        },
        "/tempcart/{productVarianId}/{userId}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update quantity of item in temporary cart",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Update cart item quantity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product Variant ID",
                        "name": "productVarianId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cart item updated",
                        "schema": {
                            "$ref": "#/definitions/handler.WebResponse"
                        }
                    },
                    "404": {
                        "description": "Cart item not found",
                        "schema": {
                            "$ref": "#/definitions/handler.WebResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Remove product variant from temporary cart",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Remove item from cart",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product Variant ID",
                        "name": "productVarianId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Item removed from cart",
                        "schema": {
                            "$ref": "#/definitions/handler.WebResponse"
                        }
                    },
                    "404": {
                        "description": "Cart item not found",
                        "schema": {
                            "$ref": "#/definitions/handler.WebResponse"
                        }
                    }
                }
            }
        },
        "/tempcart/{userId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all temporary cart items for a specific user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Get cart items by user ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cart items",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/entity.TempCart"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/handler.WebResponse"
                        }
                    }
                }
            }
        },
        "/transaction": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve all transactions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Get all transactions",
                "responses": {
                    "200": {
                        "description": "Transactions list",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/entity.Transaction"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.CreateOrderDetailRequest": {
            "type": "object",
            "properties": {
                "order_detail_price": {
                    "type": "number",
                    "example": 15000
                },
                "order_detail_product_varian_id": {
                    "type": "string",
                    "example": "0058ae56cc7a089dc710b0fff0f1e312"
                },
                "order_detail_qty": {
                    "type": "integer",
                    "example": 1
                },
                "order_detail_subtotal": {
                    "type": "number",
                    "example": 15000
                }
            }
        },
        "entity.CreateOrderRequest": {
            "type": "object",
            "properties": {
                "order_address_id": {
                    "type": "string",
                    "example": ""
                },
                "order_customer_id": {
                    "type": "string",
                    "example": "1bee61b0-c11f-11f0-9feb-482ae3a0bcc9"
                },
                "order_delivery_type": {
                    "type": "string",
                    "example": "pickup"
                },
                "order_details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.CreateOrderDetailRequest"
                    }
                },
                "order_discount": {
                    "type": "number",
                    "example": 0
                },
                "order_notes": {
                    "type": "string",
                    "example": ""
                },
                "temp_cart_order_id": {
                    "type": "string",
                    "example": "ORDER-GUEST-1763326901093-JEGMFSW"
                }
            }
        },
        "entity.Customer": {
            "type": "object",
            "properties": {
                "alamat": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.CustomerAddress"
                    }
                },
                "customer_class": {
                    "type": "string"
                },
                "customer_code": {
                    "type": "string"
                },
                "customer_create_at": {
                    "type": "string"
                },
                "customer_dob": {
                    "$ref": "#/definitions/sql.NullString"
                },
                "customer_email": {
                    "type": "string"
                },
                "customer_gender": {
                    "type": "string"
                },
                "customer_id": {
                    "type": "string"
                },
                "customer_last_status": {
                    "type": "integer"
                },
                "customer_major_id": {
                    "type": "string"
                },
                "customer_name": {
                    "type": "string"
                },
                "customer_password": {
                    "type": "string"
                },
                "customer_phonenumber": {
                    "type": "string"
                },
                "customer_profile_pic": {
                    "type": "string"
                },
                "customer_profile_pic_path": {
                    "type": "string"
                },
                "customer_status": {
                    "type": "integer"
                },
                "customer_update_at": {
                    "type": "string"
                },
                "jurusan": {
                    "$ref": "#/definitions/entity.Major"
                }
            }
        },
        "entity.CustomerAddress": {
            "type": "object",
            "properties": {
                "address_city": {
                    "type": "string"
                },
                "address_city_id": {
                    "type": "string"
                },
                "address_create_at": {
                    "type": "string"
                },
                "address_customer_id": {
                    "type": "string"
                },
                "address_district": {
                    "type": "string"
                },
                "address_district_id": {
                    "type": "string"
                },
                "address_id": {
                    "type": "string"
                },
                "address_main": {
                    "type": "integer"
                },
                "address_name": {
                    "type": "string"
                },
                "address_postal_code": {
                    "type": "string"
                },
                "address_province": {
                    "type": "string"
                },
                "address_province_id": {
                    "type": "string"
                },
                "address_text": {
                    "type": "string"
                },
                "address_update_at": {
                    "type": "string"
                },
                "address_village": {
                    "type": "string"
                },
                "address_village_id": {
                    "type": "string"
                }
            }
        },
        "entity.CustomerOrder": {
            "type": "object",
            "properties": {
                "address": {
                    "$ref": "#/definitions/entity.CustomerAddress"
                },
                "customer": {
                    "$ref": "#/definitions/entity.CustomerResponse"
                },
                "orderDetail": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.CustomerOrderDetail"
                    }
                },
                "order_address_id": {
                    "type": "string"
                },
                "order_cancel_notes": {
                    "type": "string"
                },
                "order_create_at": {
                    "type": "string"
                },
                "order_customer_id": {
                    "type": "string"
                },
                "order_delivery_type": {
                    "type": "string"
                },
                "order_discount": {
                    "type": "number"
                },
                "order_finished_by": {
                    "type": "string"
                },
                "order_finished_datetime": {
                    "$ref": "#/definitions/sql.NullTime"
                },
                "order_id": {
                    "type": "string"
                },
                "order_inv_number": {
                    "type": "string"
                },
                "order_notes": {
                    "type": "string"
                },
                "order_processed_by": {
                    "type": "string"
                },
                "order_processed_datetime": {
                    "$ref": "#/definitions/sql.NullTime"
                },
                "order_status": {
                    "type": "integer"
                },
                "order_subtotal": {
                    "type": "number"
                },
                "order_total": {
                    "type": "number"
                },
                "order_total_item": {
                    "type": "integer"
                }
            }
        },
        "entity.CustomerOrderDetail": {
            "type": "object",
            "properties": {
                "order_detail_id": {
                    "type": "string"
                },
                "order_detail_parent_id": {
                    "type": "string"
                },
                "order_detail_price": {
                    "type": "number"
                },
                "order_detail_product_varian_id": {
                    "type": "string"
                },
                "order_detail_qty": {
                    "type": "integer"
                },
                "order_detail_subtotal": {
                    "type": "number"
                }
            }
        },
        "entity.CustomerResponse": {
            "type": "object",
            "properties": {
                "alamat": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.CustomerAddress"
                    }
                },
                "customer_class": {
                    "type": "string"
                },
                "customer_code": {
                    "type": "string"
                },
                "customer_create_at": {
                    "type": "string"
                },
                "customer_dob": {
                    "$ref": "#/definitions/sql.NullString"
                },
                "customer_email": {
                    "type": "string"
                },
                "customer_gender": {
                    "type": "string"
                },
                "customer_id": {
                    "type": "string"
                },
                "customer_last_status": {
                    "type": "integer"
                },
                "customer_major_id": {
                    "type": "string"
                },
                "customer_name": {
                    "type": "string"
                },
                "customer_phonenumber": {
                    "type": "string"
                },
                "customer_profile_pic": {
                    "type": "string"
                },
                "customer_profile_pic_path": {
                    "type": "string"
                },
                "customer_status": {
                    "type": "integer"
                },
                "customer_update_at": {
                    "type": "string"
                },
                "jurusan": {
                    "$ref": "#/definitions/entity.MajorResponse"
                }
            }
        },
        "entity.DashboardStats": {
            "type": "object",
            "properties": {
                "monthly_sales": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.MonthlySalesData"
                    }
                },
                "top_products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.TopProductData"
                    }
                },
                "total_customers": {
                    "type": "integer"
                },
                "total_sales": {
                    "type": "number"
                },
                "total_transactions": {
                    "type": "integer"
                }
            }
        },
        "entity.Login": {
            "type": "object",
            "required": [
                "user_email",
                "user_password"
            ],
            "properties": {
                "user_device_metadata": {
                    "type": "string"
                },
                "user_email": {
                    "type": "string"
                },
                "user_fcmtoken": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "user_password": {
                    "type": "string"
                }
            }
        },
        "entity.Major": {
            "type": "object",
            "properties": {
                "major_id": {
                    "type": "string"
                },
                "major_name": {
                    "type": "string"
                }
            }
        },
        "entity.MajorResponse": {
            "type": "object",
            "properties": {
                "major_id": {
                    "type": "string"
                },
                "major_name": {
                    "type": "string"
                }
            }
        },
        "entity.MonthlySalesData": {
            "type": "object",
            "properties": {
                "month": {
                    "type": "integer"
                },
                "month_name": {
                    "type": "string"
                },
                "total_sales": {
                    "type": "number"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "entity.Pegawai": {
            "type": "object",
            "properties": {
                "pegawai_code": {
                    "type": "string"
                },
                "pegawai_gender": {
                    "type": "string"
                },
                "pegawai_id": {
                    "type": "string"
                },
                "pegawai_name": {
                    "type": "string"
                },
                "pegawai_phonenumber": {
                    "type": "string"
                }
            }
        },
        "entity.Product": {
            "type": "object",
            "properties": {
                "category_name": {
                    "type": "string"
                },
                "product_category_id": {
                    "type": "string"
                },
                "product_code": {
                    "type": "string"
                },
                "product_create_at": {
                    "type": "string"
                },
                "product_delete_at": {
                    "type": "string"
                },
                "product_desc": {
                    "type": "string"
                },
                "product_id": {
                    "type": "string"
                },
                "product_name": {
                    "type": "string"
                },
                "product_photo": {
                    "type": "string"
                },
                "product_update_at": {
                    "type": "string"
                },
                "varian": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Varian"
                    }
                }
            }
        },
        "entity.TempCart": {
            "type": "object",
            "properties": {
                "product_varian": {
                    "$ref": "#/definitions/entity.Varian"
                },
                "temp_cart_id": {
                    "type": "string"
                },
                "temp_cart_order_id": {
                    "type": "string"
                },
                "temp_cart_product_varian_id": {
                    "type": "string"
                },
                "temp_cart_qty": {
                    "type": "integer"
                },
                "temp_cart_user_id": {
                    "type": "string"
                }
            }
        },
        "entity.TopProductData": {
            "type": "object",
            "properties": {
                "product_id": {
                    "type": "string"
                },
                "product_name": {
                    "type": "string"
                },
                "total_quantity": {
                    "type": "integer"
                },
                "total_sales": {
                    "type": "number"
                },
                "variant_name": {
                    "type": "string"
                }
            }
        },
        "entity.Transaction": {
            "type": "object",
            "properties": {
                "customer": {
                    "$ref": "#/definitions/entity.CustomerResponse"
                },
                "trans_create_at": {
                    "type": "string"
                },
                "trans_customer_id": {
                    "type": "string"
                },
                "trans_detail": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.TransactionDetail"
                    }
                },
                "trans_discount": {
                    "type": "number"
                },
                "trans_id": {
                    "type": "string"
                },
                "trans_invoice": {
                    "type": "string"
                },
                "trans_order_id": {
                    "type": "string"
                },
                "trans_product_total": {
                    "type": "integer"
                },
                "trans_qty_total": {
                    "type": "integer"
                },
                "trans_received_total": {
                    "type": "number"
                },
                "trans_refund_total": {
                    "type": "number"
                },
                "trans_status": {
                    "type": "integer"
                },
                "trans_subtotal": {
                    "type": "number"
                },
                "trans_total": {
                    "type": "number"
                },
                "trans_user_id": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/entity.User"
                }
            }
        },
        "entity.TransactionDetail": {
            "type": "object",
            "properties": {
                "trans_detail_id": {
                    "type": "string"
                },
                "trans_detail_parent_id": {
                    "type": "string"
                },
                "trans_detail_price": {
                    "type": "number"
                },
                "trans_detail_product_varian_id": {
                    "type": "string"
                },
                "trans_detail_qty": {
                    "type": "integer"
                },
                "trans_detail_subtotal": {
                    "type": "number"
                }
            }
        },
        "entity.User": {
            "type": "object",
            "properties": {
                "pegawai": {
                    "$ref": "#/definitions/entity.Pegawai"
                },
                "user_email": {
                    "type": "string"
                },
                "user_has_mobile_access": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                },
                "user_password": {
                    "type": "string"
                },
                "user_pegawai_id": {
                    "type": "string"
                },
                "user_role_id": {
                    "type": "string"
                }
            }
        },
        "entity.Varian": {
            "type": "object",
            "properties": {
                "product_id": {
                    "type": "string"
                },
                "product_name": {
                    "type": "string"
                },
                "product_varian_id": {
                    "type": "string"
                },
                "product_varian_price": {
                    "type": "integer"
                },
                "product_varian_qty_booth": {
                    "type": "integer"
                },
                "product_varian_qty_left": {
                    "type": "integer"
                },
                "product_varian_qty_warehouse": {
                    "type": "integer"
                },
                "varian_id": {
                    "type": "string"
                },
                "varian_name": {
                    "type": "string"
                }
            }
        },
        "entity.VersionAdmin": {
            "type": "object",
            "properties": {
                "version_chagelog": {
                    "type": "string"
                },
                "version_code": {
                    "type": "integer"
                },
                "version_datetime": {
                    "type": "string"
                },
                "version_id": {
                    "type": "integer"
                },
                "version_number": {
                    "type": "string"
                }
            }
        },
        "entity.VersionShop": {
            "type": "object",
            "properties": {
                "version_chagelog": {
                    "type": "string"
                },
                "version_code": {
                    "type": "integer"
                },
                "version_datetime": {
                    "type": "string"
                },
                "version_id": {
                    "type": "integer"
                },
                "version_number": {
                    "type": "string"
                }
            }
        },
        "handler.WebResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "sql.NullString": {
            "type": "object",
            "properties": {
                "string": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if String is not NULL",
                    "type": "boolean"
                }
            }
        },
        "sql.NullTime": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.2.0",
	Host:             "127.0.0.1:3000",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "E-Canteen Cashier API",
	Description:      "API documentation for E-Canteen Cashier System - A comprehensive canteen management solution",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
